-- =========================
-- INITIAL SCHEMA (v1)
-- =========================

-- USERS
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_email ON users (username);

-- EMPLOYEES
CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    pin_code INTEGER,
    designation VARCHAR(100),
    bps INTEGER,
    nature_of_appointment VARCHAR(50),
    account_no VARCHAR(30),
    cnic_no VARCHAR(20) UNIQUE,
    date_of_birth DATE,
    date_of_joining DATE,
    date_of_retirement DATE
);

-- PAYSLIPS
CREATE TABLE payslips (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
    month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
    year INTEGER NOT NULL,
    basic_pay NUMERIC(10,2) NOT NULL,
    total_allowances NUMERIC(10,2) DEFAULT 0,
    total_deductions NUMERIC(10,2) DEFAULT 0,
    gross_pay NUMERIC(10,2) GENERATED ALWAYS AS (basic_pay + total_allowances) STORED,
    net_pay NUMERIC(10,2) GENERATED ALWAYS AS (basic_pay + total_allowances - total_deductions) STORED,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    json JSONB,
    upload_id UUID,
    name TEXT,
    cnic_no TEXT,
    designation TEXT,
    bps INTEGER,
    nature_of_appointment TEXT,
    account_no TEXT,
    pin_code INTEGER,
    date_of_birth DATE,
    date_of_joining DATE,
    date_of_retirement DATE,
    UNIQUE (employee_id, month, year)
);

-- SESSIONS
CREATE TABLE sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);
CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);
