BEGIN;
CREATE TABLE ug_batch (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester integer NOT NULL,
    year integer NOT NULL,
    department varchar(100) NOT NULL,
    section varchar(100) NOT NULL,
    status varchar(100) NOT NULL DEFAULT 'open',
    created_by integer NOT NULL REFERENCES users (id),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    closed_at timestamptz,
    closed_by integer REFERENCES users (id)
);
CREATE TABLE ug_batch_student (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id integer NOT NULL REFERENCES ug_batch (id) ON DELETE CASCADE,
    reg_number varchar(50) NOT NULL UNIQUE,
    name varchar(256) NOT NULL,
    ug_form_submitted boolean NOT NULL DEFAULT FALSE,
    fee_verified boolean NOT NULL DEFAULT FALSE,
    verified_by integer REFERENCES users (id),
    verified_at timestamptz
);
COMMIT;

