export const DEPARTMENTS = [
    'B.Sc. Agricultural Engineering',
    'Doctor of Veterinary Medicine',
    'B.Sc. (Hons.) Home Economics',
    'B.Sc. (Hons.) Human Nutrition and Dietetics',
    'B.Sc. Food Engineering',
    'B.Sc. Textile Engineering Technology',
    'B.Sc. Energy Systems Engineering',
    'B.Sc. Environmental Engineering',
    'Doctor of Pharmacy (Pharm-D)',
    'Bachelor of Business Administration (BBA)',
    'BS (Bio-Informatics)',
    'BS (Biostatistics)',
    'BS (Computer Science)',
    'BS (Information Technology)',
    'BS (Software Engineering)',
    'BBA (Agribusiness)',
    'B.Sc. (Hons.) Poultry Sciences',
    'B.Sc. (Hons.) Agricultural and Resource Economics',
    'B.Sc. (Hons) Agriculture (First Four Semesters)',
    'B.Sc. (Hons) Agriculture Major Agronomy',
    'B.Sc. (Hons.) Agriculture, Major Agri. Biotechnology',
    'B.Sc. (Hons.) Agriculture, Major Entomology',
    'B.Sc. (Hons.) Agriculture Major Forestry',
    'B.Sc. (Hons) Agriculture Major Horticulture',
    'B.Sc. (Hons.) Agriculture Major Plant Pathology',
    'B.Sc. (Hons.) Agriculture Major Plant Breeding and Genetics',
    'B.Sc. (Hons.) Agriculture Major Seed Science and Technology',
    'B.Sc. (Hons.) Agriculture Major Soil Science',
    'B.Sc. (Hons.) Marketing and Agribusiness',
    'BS Forestry',
    'B.Sc. (Hons.) Agricultural and Resource Economics (Composite Degree Program)',
    'B.Sc. (Hons) Agriculture, Major Agri. Extension',
    'B.Sc. (Hons.) Animal Sciences under common admission in B.Sc. (Hons.) Agriculture at Faculty of Animal Husbandry',
    'B.Sc. (Hons.) Environmental Science',
    'B.S Microbiology',
    'B.Sc. (Hons.) Environmental Science',
    'B.Sc. (Hons.) Microbiology',
    'BS Animal Sciences',
    'BS Dairy Science',
    'B.Sc. (Hons.) Food Science and Technology',
    'BS (Chemistry)',
    'BS (Biochemistry)',
    'BS (Botany)',
    'BS (Physics)',
    'BS (Zoology)',
    'BS Mathematics',
    'BS Statistics',
    'BS English (Language and Literature)',
    'BS Commerce',
    'BS Economics',
    'BS Forestry',
    'BS Sociology',
    'Bachelor of Fine Arts (BFA)',
    'Bachelor of Education (Hons.)',
    'BS (Data Science)',
    'BS (Artificial Intelligence)',
    'BS Fisheries and Aquaculture',
    'BS Data Analytics',
    'BS Development Studies',
    'Bachelor of Fashion Design',
    'BS Criminology',
];

export const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8];
export const SECTIONS = ['morning', 'evening'];
